In [19]:
import pandas as pd
import re

In [88]:
df = pd.read_excel(fr"C:\Users\antsharma\Downloads\PQ_Challenge_1_Problem.xlsx", skiprows = 1, nrows=10,  usecols= 'B')
df

          String
0  a12gh I 5 @ #
1      0ui^12965
2         pqw%^*
3          97531
4      a1b2c3d45
5  a1\nb6 c9\nd4
6            %6%
7      4 5 6 \n7
8     0@130&xyz2

In [89]:
def get_digits(text):
    return ''.join(re.findall(r'\d+', str(text)))
    
df['Digits'] = df['String'].apply(get_digits)
df['Sum of Digits'] = df['String'].apply(lambda x: sum([int(i) for i in get_digits(x)]))
df['Sum of Digits 2'] = df['Digits'].apply(lambda x: sum([int(i) for i in x]))

In [90]:
df

          String  Digits  Sum of Digits  Sum of Digits 2
0  a12gh I 5 @ #     125              8                8
1      0ui^12965  012965             23               23
2         pqw%^*                      0                0
3          97531   97531             25               25
4      a1b2c3d45   12345             15               15
5  a1\nb6 c9\nd4    1694             20               20
6            %6%       6              6                6
7      4 5 6 \n7    4567             22               22
8     0@130&xyz2   01302              6                6